export enum projectConstants {
  GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS',
  GET_ALL_PROJECTS_LOADING = ' GET_ALL_PROJECTS_LOADING',
  GET_ALL_PROJECTS_FAILED = 'GET_ALL_PROJECTS_FAILED',
  GET_PROJECT_REPORT_SUCCESS = 'GET_PROJECT_REPORT_SUCCESS',
  GET_PROJECT_REPORT_LOADING = ' GET_PROJECT_REPORT_LOADING',
  GET_PROJECT_REPORT_FAILED = 'GET_PROJECT_REPORT_FAILED',
  PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS',
  PROJECT_CREATE_LOADING = 'PROJECT_CREATE_LOADING',
  PROJECT_CREATE_FAILED = 'PROJECT_CREATE_FAILED',
  PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS',
  PROJECT_UPDATE_FAILED = 'PROJECT_UPDATE_FAILED',
  PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS',
  PROJECT_DELETE_LOADING = 'PROJECT_DELETE_LOADING',
  PROJECT_DELETE_FAILED = 'PROJECT_DELETE_FAILED',
  PROJECT_CLEAR_ERROR_MESSAGE = 'PROJECT_CLEAR_ERROR_MESSAGE'
}
