export enum userConstants {
    GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_LOADING = 'GET_ALL_USERS_LOADING',
    GET_ALL_USER_FAILED = "GET_ALL_USER_FAILED",
    USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS',
    USER_CREATE_FAILED = 'USER_CREATE_FAILED',
    USER_CREATE_LOADING = 'USER_CREATE_LOADING',
    USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
    USER_UPDATE_LOADING = 'USER_UPDATE_LOADING',
    USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS',
    USER_DELETE_FAILED = 'USER_DELETE_FAILED',
    USER_DELETE_LOADING = 'USER_DELETE_LOADING',
    USER_CLEAR_ERROR_MESSAGE = 'USER_CLEAR_ERROR_MESSAGE'
}